# image will be published to ghcr.io/<user>/<name>
name: ternion-linux
# description will be included in the image's metadata
description: An atomic Trinity desktop

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-nvidia
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  # trinity is installed in /opt/trinity, so we need to symlink this to somewhere that can be stored in the immutable system
  - type: script
    snippets:
      - "mkdir -p /usr/lib/opt/trinity"
      - "mkdir -p /var/opt"
      - "ln -s /usr/lib/opt/trinity /var/opt/trinity"
      # - "setenforce 0" # fucking SELinux cucks TDM for some reason because SELinux always fucks everything up
      # if you know how to fix this properly please do idk how to write SELinux policies
      # I added this to /etc/ to bypass it permanently so hopefully that should work...
  # prepare repos first
  - type: rpm-ostree
    install:
      https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-41.noarch.rpm
      https://mirrors.rpmfusion.org/free/fedora/rpmfusion-nonfree-release-41.noarch.rpm
  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - trinity.repo
    keys:
      # - trinity-key
    install:
      # - micro
      # - starship
      # - http://mirror.ppa.trinitydesktop.org/trinity/rpm/f41/trinity-r14/RPMS/noarch/trinity-repo-14.1.3-1.fc41.noarch.rpm
      # somehow this doesn't install X11...
      - xorg-x11-server-Xorg
      # the desktop
      - trinity-desktop
      # all available themes
      - trinity-tde-style-baghira
      - trinity-tde-style-domino
      - trinity-tde-style-ia-ora
      - trinity-tde-style-lipstik
      - trinity-tde-style-polyester
      - trinity-tde-style-qtcurve
      - trinity-twin-style-crystal
      - trinity-twin-style-dekorator
      - trinity-twin-style-fahrenheit
      - trinity-twin-style-mallory
      - trinity-twin-style-suse2
      # we don't use su around these parts
      - trinity-tdesudo
      # Compiz because this may be preferable to twin - idk if the Trinity decorator is available for Fedora though :(
      - compiz
      - compiz-manager
      - compiz-plugins-main
      - compiz-plugins-extra
      - compiz-plugins-experimental
      - ccsm
      - emerald
      - emerald-themes
      # apps I want (very opinionated) & more fluff
      - trinity-basket
      - trinity-amarok
      - trinity-amarok-konqueror
      - trinity-amarok-visualisation
      - trinity-gtk-qt-engine
      - trinity-gtk3-tqt-engine
      - trinity-codeine
      - trinity-gwenview
      - trinity-krusader
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
  - type: systemd
    system:
      enabled:
        - ternion-symlink.service # creates the /var/opt/trinity symlink on each boot; cursed workaround but it'll hopefully do
        - tdm.service
  - type: brew
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

